### ISSUE TITLE
The most recent commit (828fc305) fails to build on KDE Neon 5.22

### ISSUE THREAD

**Issue by Fish-Git** [SDL-Hercules-390/hyperion#401]
Bill, &nbsp; &nbsp; (@wrljet)

I'm unable to get a clean build of Hercules on my KDE Neon 5.22 system with your latest commit (828fc305d986ede8c864cb4f5fb2b28dd5c7c2f0):

```
neon@vm-kdeneon-520:~/hercules/hercules-0$ git rev-parse HEAD
828fc305d986ede8c864cb4f5fb2b28dd5c7c2f0
```

* _**osversion:**_ KDE neon User Edition 5.22
* _**kernelversion:**_ 5.8.0-59-generic
* _**gcc version:**_ 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
* _**clang version:**_ 10.0.0-4ubuntu1

&nbsp;
Apparently something isn't right with the `ltdl.c` file:
&nbsp;
```
In file included from hostinfo.c:21:
/usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: warning: "The <sys/sysctl.h> header is deprecated and will be removed." [-W#warnings]
ltdl.c:412:15: error: incomplete type 'void' is not assignable
ltdl.c:437:13: error: incomplete type 'void' is not assignable
ltdl.c:442:13: error: incomplete type 'void' is not assignable
ltdl.c:877:39: error: use of undeclared identifier 'LTDL_OBJDIR'
ltdl.c:2761:13: warning: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
ltdl.c:3110:13: warning: assigning to 'char *' from 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
ltdl.c:3163:13: warning: implicitly declaring library function 'isalnum' with type 'int (int)' [-Wimplicit-function-declaration]
ltdl.c:3305:28: warning: assigning to 'char *' from 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
ltdl.c:3483:7: warning: assigning to 'char *' from 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
make[2]: *** [Makefile:2506: ltdl.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:2556: all-recursive] Error 1
make: *** [Makefile:1894: all] Error 2
```

&nbsp;
### Full build log:

* [make.log](https://github.com/SDL-Hercules-390/hyperion/files/6744590/make.log)
&nbsp;

**Comment by Fish-Git** [comment]
Temporary workaround is to fall back to commit 3fad697f4104c0cee298ef63b764b3948c2c5cee.

**Comment by wrljet** [comment]
Fish,

It works fine for me.

Your `make.log` shows you are using Clang, while I am using gcc on that system.
So that's one difference.  I'll test that here shortly.

But, `ltdl.c` shouldn't even be compiling on that system.

Can you post the `config.log` from your build.

Bill

**Comment by mcisho** [comment]
It doesn't work for me on Fedora 34 using gcc version 11.1.1 20210531 (Red Hat 11.1.1-3). I have the same symptoms as Fish, the ltdl.c errors. I started with a git clone with no changes.

Ian

**Comment by wrljet** [comment]
Did you run configure?

I didn't test on Fedora, but did on CentOS.
But I expect it will work.

**Comment by mcisho** [comment]
These are the command I used:-

git clone https://github.com/SDL-Hercules-390/hyperion.git /home/irs/Source/Hercules.SDL/hyperion

cd /home/irs/Source/Hercules.SDL/hyperion

./util/bldlvlck

./configure \
    --prefix=/home/irs/Hercules.run \
    --enable-optimization="-O2" \
    --disable-object-rexx \
    --disable-regina-rexx

make

Hers is the config.log

[config.log](https://github.com/SDL-Hercules-390/hyperion/files/6748925/config.log)

**Comment by wrljet** [comment]
OK, I see a possible issue.  More in a bit...

**Comment by wrljet** [comment]
OK, what's happened, all my building has been focused on using my Hercules-Helper project 
which removes all the system dependent aspects of setup, configure, and building.

As such, I completely failed to run a simple by-hand build.  And therefore forgot that my new
autohell stuff is now relying on the system specific `libtool` on most systems.
(Which is a development tool package that must be installed.)

So...

- Fish, please run  `sudo apt install libtool`.
Then rerun `configure`, `make clean`, and `make`.

- mcisho, please run `sudo dnf install libtool-ltdl-devel` and rerun your build.

I will add a check for this to `bldlvlck`.
And I will write up some documentation edits for our build instructions page.

Bill

**Comment by mcisho** [comment]
Installing libtool-ltdl-devel fixed the problem for me.

Lots of warnings re static and inline, but I guess Fish is working on that, amongst many other things!

Ian

**Comment by Fish-Git** [comment]
> * Fish, please run  `sudo apt install libtool`.

Thanks! That did the trick for me.

> Lots of warnings re static and inline, ...

I'm not seeing that at all, which is what _bothers me **greatly!**_

After successfully building Hercules with my patch applied, Hercules built _cleanly._ No errors or warning at all.

But of course as soon as I tried actually _using_ (running) it to try and do something useful (like to run a simple test that required starting a CPU and executing instructions), _BOOM!_ Immediate crash. [(With the gdb analysis of the resulting core file being identical to the one I already previously posted in my comment to issue #400)](https://github.com/SDL-Hercules-390/hyperion/issues/400#issuecomment-872072944).

_How am I suppose to address an obvious **FATAL** problem that I'm not even warned might exist?_

&nbsp; &nbsp; `:(`

**Comment by wrljet** [comment]
Fish,

> After successfully building Hercules with my patch applied, Hercules built cleanly. No errors or warning at all.

In the log you posted earlier, you appeared to be using Clang.  That might explain differences in warnings and nags.
(Although I believe they strive for compatibility with gcc, re: switches/keywords/etc and their behavior.)

> _How am I suppose to address an obvious **FATAL** problem that I'm not even warned might exist?_

LOL!  You've been cussing at computers for **decades**, I assume.  Lots of programs compile but don't work. :-)

Bill

**Comment by Fish-Git** [comment]
> LOL! You've been cussing at computers for **decades**, I assume.

What?! _ME?!_ Hell no! How dare you. I don't cuss at computers at all, Bill.

I _HAVE_ however been cussing at stupid _software_ written by stupid _people_ for probably several decades now, yes. But computers? Nah. They're totally innocent. &nbsp;`;-)`

**Comment by Fish-Git** [comment]
**FYI:** &nbsp;I'll keep this issue open until I see some commits by you to address the `bldlvlck` and documentation issues [you promised to fix](https://github.com/SDL-Hercules-390/hyperion/issues/401#issuecomment-872353070).

Once I see those I'll close this issue.

Or you can close it yourself since I did assign it to _you_ after all.

**Comment by Fish-Git** [comment]
> > After successfully building Hercules with my patch applied, Hercules built cleanly. No errors or warning at all.
> 
> In the log you posted earlier, you appeared to be using Clang. That might explain differences in warnings and nags.

You were right. Using clang was the difference. When I switched to building using gcc instead, I started getting the expected warnings.

Which is kind of ironic. The whole purpose of me switching to using clang instead of gcc (which I did quite a long while ago) was to avoid being subjected to too many unhelpful gcc warnings that IMO didn't warrant being warned about. (Clang seems to do a much better job of that IMO.)

But this time it's just the opposite: gcc issues a warning that is apparently quite useful _(not to mention **crtically important** in this particular case!)_, whereas clang doesn't!

(Sigh!) &nbsp;You can't win for losing I guess. &nbsp; `:(`

**Comment by rgschmi** [comment]
Installing libtool fixed the make issue, but when I try to run Hercules I get the following:

Error while loading shared libraries: libherc.so: cannot load shared object file: no such file or directory

Am I missing something?   I'm running openSUSE 15.3 leap.  I'm not sure what Hercules build I have since I can't do a Version command, but I did the git on June 29.

**Comment by wrljet** [comment]
BobGSchmidt wrote (but the post seems to have disappeared):

> Installing libtool fixed the make issue, but when I try to run Hercules I get the following:
>
> Error while loading shared libraries: libherc.so: cannot load shared object file: no such file or directory
>
> Am I missing something? I'm running openSUSE 15.3 leap. I'm not sure what Hercules build I have since I can't do a Version > > command, but I did the git on June 29.

Bob,
I just rechecked this on my openSUSE 15.3 VM, and it worked OK.
I did use Hercules-Helper, but that shouldn't make any difference.

Can you please post the exact commands you used to configure and build Hercules.

---

There is however a "bug" someplace that was introduced in openSUSE 15.3 that wasn't
present with 15.2.  It affects the Regina REXX integration and makes the build tests not
work correctly.  The final QUIT command to Hercules doesn't take, unless a Ctrl+D is entered
from the keyboard.  I've been looking for this bug for a while now on-and-off but haven't
found it yet.

Thanks, Bill

**Comment by rgschmi** [comment]
I made a dumb mistake (several, actually) and had to install openSUSE 15.3 instead of upgrading from 15.2.  Of course I forgot about the external libraries Hercules now needs, so my make failed.  Hercules builds just fine on my old 15.2 openSUSE.  When I realized my mistake, I deleted my post.  I haven't actually run the Hercules build on my 15.2 system yet.

Now I just have to remember how I built the external libraries.  I'm nowhere near a linux expert...

**Comment by Fish-Git** [comment]
> Now I just have to remember how I built the external libraries. I'm nowhere near a linux expert...

It's a fairly simple and straightforward one-time procedure, documented here:

* [README.EXTPKG](https://github.com/SDL-Hercules-390/hyperion/blob/master/readme/README.EXTPKG.md)

The `extpkgs.sh` helper script (which you can download from our **[gists repository](https://github.com/SDL-Hercules-390/gists))** makes it trivially easy to do.

The only hard part is remembering to use the `--enable-extpkgs=<dir>` option on your `./configure` command each time you build Hercules. **(*)**

HTH

&nbsp;
**(*)** &nbsp; _Or, in lieu of that, you can of course simply point your `LIBRARY_PATH` and `CPATH` environment variables to your `./extpkgs/lib` and `./extpkgs/include` directories instead, as documented in the above [README](https://github.com/SDL-Hercules-390/hyperion/blob/master/readme/README.EXTPKG.md)). Most people however, find it easier to just specify the extra `./configure` option instead each time they build Hercules._ **(\*\*)**

**(\*\*)** &nbsp; _Permanently setting your `LIBRARY_PATH` and `CPATH` environment variables to the appropriate extpkgs directory relieves you from always having to specify that extra ./configure option._

**Comment by wrljet** [comment]
I would recommend you give my Hercules-Helper a try.
It knows how to build on openSUSE.

https://github.com/wrljet/hercules-helper

Bill

**Comment by rgschmi** [comment]
I used the extpkgs.sh script and it worked like a charm.  Hercules Helper is next on my list.

However, I cannot IPL z/OS  with Hercules build g828fc305-modified.  I'm not sure how the modified got there, as  I did not run autogen.  Shortly after IPL, Hercules goes into a loop (I think) with no I/O activity at all.  Build g32d12379 works ok. It happens to two openSUSE machines, an old one at leap 15.2 and my new one at leap 15.3.  I'd be happy to gather any requested documentation.

**Comment by Fish-Git** [comment]
> However, I cannot IPL z/OS with Hercules build g828fc305-modified.

You're a few commits behind. You need to either do a refresh of your repository to pick up the last few commits or else discard it and do a fresh re-clone instead.

> I'm not sure how the modified got there, as I did not run autogen.

Me neither. It only seems to happen on Linux and I'm not sure why. I haven't figured it out yet. Doing a `./configure` should _not_ be modifying any repository files. Maybe it has something to do with Bill's autotools changes? Bill? Any ideas?

**Comment by Fish-Git** [comment]
> I'm not sure how the modified got there, as I did not run autogen.

What does `"git ls-files -m"` show?

**Comment by rgschmi** [comment]
I see the two libltdl lines descrived in #403.

**Comment by wrljet** [comment]
Yes, those two files got checked in by mistake.  I will remove them.

**Comment by Fish-Git** [comment]
I believe this issue has now been resolved. Closing.
