### ISSUE TITLE
Fails to build on Linux on s390x

### ISSUE THREAD

**Issue by moshix** [SDL-Hercules-390/hyperion#419]
I am trying to build today's hyperion repository on Centos 7 on s390x with gcc 4.8.5. I get the following errors during make:

```
ltdl.c:412:7: error: invalid use of void expression
       dest[i] = src[i];
       ^
ltdl.c: In function ‘rpl_memmove’:
ltdl.c:437:9: warning: dereferencing ‘void *’ pointer [enabled by default]
     dest[i] = src[i];
         ^
ltdl.c:437:18: warning: dereferencing ‘void *’ pointer [enabled by default]
     dest[i] = src[i];
                  ^
ltdl.c:437:5: error: invalid use of void expression
     dest[i] = src[i];
     ^
ltdl.c:440:5: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
     for (i = size -1; i >= 0; --i)
     ^
ltdl.c:442:9: warning: dereferencing ‘void *’ pointer [enabled by default]
     dest[i] = src[i];
         ^
ltdl.c:442:18: warning: dereferencing ‘void *’ pointer [enabled by default]
     dest[i] = src[i];
                  ^
ltdl.c:442:5: error: invalid use of void expression
     dest[i] = src[i];
     ^
ltdl.c: At top level:
ltdl.c:877:39: error: ‘LTDL_OBJDIR’ undeclared here (not in a function)
 static  const char  objdir[]        = LTDL_OBJDIR;
                                       ^
```

**Comment by wrljet** [comment]
Moshe,

Please see the Hercules build help at this webpage: `https://sdl-hercules-390.github.io/html/hercinst.html#install`

Scroll down a ways and you'll see the list of required packages for various systems.
CentOS 7 is in there but I've only tested it running on x86_64.

Likely you need to run:
```
sudo yum -y install libtool-ltdl-devel
```

A `bldlvchk` improvement is *coming soon* to cover your particular situation.

Bill

**Comment by wrljet** [comment]
Recent update to bldlvlck in commit https://github.com/SDL-Hercules-390/hyperion/commit/6b59bf6dd66b3adaca38b848cc41045e7d6735ef addresses libtool and ltdl.h.

Although I have not tested that on s390x.

However, other recent improvements to function inlining throughout Hercules for performance
will not build correctly with gcc 4.8.5 (at least on x86-64).

Bill

**Comment by moshix** [comment]
seems fine. thx

M
