### ISSUE TITLE
Build on RHEL 6.10 gets errors due to ULONG_PTR typedef

### ISSUE THREAD

**Issue by grahamc1** [SDL-Hercules-390/hyperion#245]
Hi
I got the following error message when building hercules 4.2.1 on RHEL 6.10:

```
In file included from x75.c:66,
                 from x75.c:134:
tcpip.h:9: error: redefinition of typedef 'ULONG_PTR'
tcpip.h:9: note: previous declaration of 'ULONG_PTR' was here
In file included from x75.c:66,
                 from x75.c:139:
tcpip.h:9: error: redefinition of typedef 'ULONG_PTR'
tcpip.h:9: note: previous declaration of 'ULONG_PTR' was here
make[2]: *** [x75.lo] Error 1
make[2]: Leaving directory `/home/graham/misc/hercules/hyperion-Release_4.2.1'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/graham/misc/hercules/hyperion-Release_4.2.1'
make: *** [all] Error 2
```
I found a workaround of:
- comment out typedef in tcpip.h
- replace all instances of "ULONG_PTR" with "unsigned long" in tcpip.c and x75.h 

This workaround got it to compile. It looks like the ULONG_PTR typedef isn't really necessary, so replacing with the underlying type fixed it.

Regards
Graham

**Comment by Fish-Git** [comment]
Fixed by commit 392a251af7d5a2e6efcca5d30f4f1b2d7b92e5f6.

Closing.

**Comment by grahamc1** [comment]
Thanks Fish, much appreciated. :-)
Graham
